/** 
 * Copyright (c) 2016 iCOMM-semi. All Rights Reserved.
 *
 * NO WARRANTY of ANY KIND is provided. This heading must NOT be removed from
 * the file.
 *
 */
#ifndef _ICMD_H_
#define _ICMD_H_

/**
 * iCMD format: INDICATOR
 *
 */
#define ICMD_INDICATOR      (0x0a)
#define STATUS_INDICATOR    (0x0b)
#define IEVT_INDICATOR      (0x0c)
#define QUERY_INDICATOR     (0x0d)
#define POLL_INDICATOR      (0x0e)

/**
 * iCMD format: HEADER
 *  - HEADER include: INDICATOR, OP, PARAMeter LENgth
 *
 */
// size
#define ICMD_INDICATOR_SIZE     (1)
#define ICMD_OP_SIZE            (1)
#define ICMD_PARAM_LEN_SIZE     (1)
#define ICMD_HEADER_LEN         (ICMD_INDICATOR_SIZE +ICMD_OP_SIZE +ICMD_PARAM_LEN_SIZE)
// index
#define ICMD_INDICATOR_INDEX    (0)
#define ICMD_OP_INDEX           (ICMD_INDICATOR_INDEX   +ICMD_INDICATOR_SIZE)
#define ICMD_PARAM_LEN_INDEX    (ICMD_OP_INDEX          +ICMD_OP_SIZE)
#define ICMD_PARAM_INDEX        (ICMD_PARAM_LEN_INDEX   +ICMD_PARAM_LEN_SIZE)

/**
 * iCMD OP
 *
 */
typedef enum {
    ICMD_OP_GAP_DEVICE_CONFIG = 0x01,
    ICMD_OP_GAP_SET_ADV_PARAM,
    ICMD_OP_GAP_SET_ADV_DATA,
    ICMD_OP_GAP_SET_ADV_ENABLE,
    ICMD_OP_GAP_SET_SCAN_PARAM,
    ICMD_OP_GAP_SET_SCAN_ENABLE,
    ICMD_OP_GAP_ADD_DEVICE_TO_WHITE_LIST,
    ICMD_OP_GAP_REMOVE_DEVICE_FROM_WHITE_LIST,      // 0x08
    ICMD_OP_GAP_SET_TX_POWER,
    ICMD_OP_GAP_GEN_RANDOM_ADDR,
    ICMD_OP_GAP_SET_RANDOM_ADDR,
    ICMD_OP_GAP_GET_PUBLIC_ADDR,
    ICMD_OP_GAP_GET_REMOTE_VERSION_INFO,
    ICMD_OP_GAP_CONNECTION_PARAM_UPD,
    ICMD_OP_GAP_DISCONNECT,
    ICMD_OP_GAP_READ_RSSI,                          // 0x10
    ICMD_OP_GAP_SECURITY_SET_KEY,
    ICMD_OP_GAP_SECURITY,
    ICMD_OP_GAP_SECURITY_PASSKEY_INPUT_CFM,
    ICMD_OP_GATTS_DATABASE_RESET,
    ICMD_OP_GATTS_ADD_SERVICE,
    ICMD_OP_GATTS_ADD_INCLUDE_SERVICE,
    ICMD_OP_GATTS_ADD_CHARACTERISTIC,
    ICMD_OP_GATTS_ADD_CHARACTERISTIC_DESCRIPTOR,    // 0x18
    ICMD_OP_GATTS_GET_VALUE,
    ICMD_OP_GATTS_SET_VALUE,
    ICMD_OP_GATTS_SERVER_INDICATE,
    ICMD_OP_GATTS_AUTHORIZE_CONFIRM,
    ICMD_OP_GATTS_AUTHORIZE_CONFIRM_WITH_VALUE,
    ICMD_OP_GATTS_PREPARE_WRITE_AUTHORIZE_CONFIRM,
    ICMD_OP_GATTS_EXECUTE_WRITE_AUTHORIZE_CONFIRM,
    ICMD_OP_WAKELOCK,                               // 0x20
    ICMD_OP_RESET,
    ICMD_OP_AES128,
    ICMD_OP_DTM_ENABLE,
    ICMD_OP_IEVT_MASK,
    ICMD_OP_ECHO_TEST,
    ICMD_OP_GEN_RAND_NUMBER,
    ICMD_OP_EFUSE_WRITE,
    ICMD_OP_EFUSE_READ,                             // 0x28
    ICMD_OP_RESERVED41,
    ICMD_OP_RESERVED42,
    ICMD_OP_TEST_RECEIVER,
    ICMD_OP_TEST_TRANSMITTER,
    ICMD_OP_TEST_END,
    ICMD_OP_RESERVED46,
    ICMD_OP_RESERVED47,
    ICMD_OP_RESERVED48,                             // 0x30
    ICMD_OP_ENGINEER_SET_UART_BAUD_RATE,
    ICMD_OP_RESERVED50,
    ICMD_OP_RESERVED51,
    ICMD_OP_ANCS_SUPPORT,
    ICMD_OP_ANCS_DISCOVER,
    ICMD_OP_ANCS_ENABLE_SOURCE,
    ICMD_OP_ANCS_ACTION,
    ICMD_OP_GAP_SET_METADATA,                       // 0x38
    ICMD_OP_GAP_SECURITY_SET_PARAM,
    ICMD_OP_XTAL_CLOAD_TUNING,
    ICMD_OP_SET_RF_INDICATION_ENABLE,
    ICMD_OP_GET_BATTERY_VOLTAGE,
    ICMD_OP_UNDEF
}   ICMD_OP;

/**
 * iEVT format
 *
 */
// size
#define IEVT_INDICATOR_SIZE     (ICMD_INDICATOR_SIZE)
#define IEVT_OP_SIZE            (1)
#define IEVT_PARAM_LEN_SIZE     (1)
#define IEVT_HEADER_LEN         (IEVT_INDICATOR_SIZE +IEVT_OP_SIZE +IEVT_PARAM_LEN_SIZE)
// index
#define IEVT_INDICATOR_INDEX    (0)
#define IEVT_OP_INDEX           (IEVT_INDICATOR_INDEX +IEVT_INDICATOR_SIZE)
#define IEVT_PARAM_LEN_INDEX    (IEVT_OP_INDEX        +IEVT_OP_SIZE)
#define IEVT_PARAM_INDEX        (IEVT_PARAM_LEN_INDEX +IEVT_PARAM_LEN_SIZE)

/**
 * STATUS format
 *
 */
// size
#define STATUS_INDICATOR_SIZE   (ICMD_INDICATOR_SIZE)
#define STATUS_OP_SIZE          (1)
#define STATUS_PARAM_LEN_SIZE   (1)
#define STATUS_HEADER_LEN       (STATUS_INDICATOR_SIZE +STATUS_OP_SIZE +STATUS_PARAM_LEN_SIZE)
// index
#define STATUS_INDICATOR_INDEX  (0)
#define STATUS_OP_INDEX         (STATUS_INDICATOR_INDEX +STATUS_INDICATOR_SIZE)
#define STATUS_PARAM_LEN_INDEX  (STATUS_OP_INDEX        +STATUS_OP_SIZE)
#define STATUS_PARAM_INDEX      (STATUS_PARAM_LEN_INDEX +STATUS_PARAM_LEN_SIZE)

// STATUS parameter
#define STATUS_PARAM_ICMD_OP_SIZE       (1)
#define STATUS_PARAM_STATUS_CODE_SIZE   (1)

#define STATUS_PARAM_ICMD_OP_INDEX      (0)
#define STATUS_PARAM_STATUS_CODE_INDEX  (STATUS_PARAM_ICMD_OP_INDEX     +STATUS_PARAM_ICMD_OP_SIZE)
#define STATUS_PARAM_RET_PARAM_INDEX    (STATUS_PARAM_STATUS_CODE_INDEX +STATUS_PARAM_STATUS_CODE_SIZE)


#ifndef IEVT_IRQ_ACTIVE
#define IEVT_IRQ_ACTIVE      0
#endif

#endif // _ICMD_OP_H_
